---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: go-demo-5
  namespace: go-demo-5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-demo-5
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: nginx_ingress_controller_requests
      describedObject:
        apiVersion: v1 #make sure you check the api version on the targeted resource using get command.
        kind: Service
        name: go-demo-5
      target:
        type: Value
        value: 50m