---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: go-demo-5
  namespace: go-demo-5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-demo-5
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: http_req_per_second_per_replica
      describedObject:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: go-demo-5
      target:
        type: Value
        value: 50m